[build]
builder = "nixpacks"
buildCommand = "cd client && npm install && npm run build && cd ../server && npm install"

[deploy]
startCommand = "cd server && NODE_ENV=production npm start"
healthcheckPath = "/api/auth/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
MONGODB_URI = "${MONGO_URL}"
CORS_ORIGIN = "*" 